### ISSUE TITLE
Problem with Async Function (need something like express next)

### ISSUE THREAD

**Issue by timenz** [idchlife/node-telegram-bot-api-middleware#1]
In the express middleware we have something like `next` parameter that we can explicit when we want to execute next middleware. Using this library I cant set middleware function to wait `async` function (like promise) to finish before execute next middleware.

Or maybe anyone can give me another aproach.

```
const response = use(() => {
  setTimeout(() => {
    console.log('I want to execute this first')
  })
}).use(() => {
  console.log('before this')
})

bot.onText(/\/t/, response)

// response
before this
I want to execute this first
```

**Comment by idchlife** [comment]
@timenz you use setTimeout function, which is executed first, but due to the nature of event loop, the function you provided to setTimeout goes way down to the execution queue. So it will be last.

I may be mistaken, since I did not visit this repository for a while.

Could you please check execution without setTimeout? Will it be executed first?

**Comment by timenz** [comment]
@idchlife with `setTimeout` I just want to show that this lib doesn't support async stuff.

**Comment by idchlife** [comment]
@timenz you could always use generator from inside functions callbacks.
That's the thing with this library. It's for generators, which can be used to do async stuff with * and yield keyword.

If you simply will execute setTimeout within function, without yield or some kind of wrapper for async/await - setTimeout in any case will not be awaited for.
